### PR TITLE
Fix opam metadata

### PR DESCRIPTION
**Pull request by fare**
Makes opam happier.

### CODE REVIEW

**Comment by bikallem** [comment]
Thanks.

**Comment by fare** [comment]
I [requested from the opam maintainers to include your project in opam])https://github.com/ocaml/opam-repository/issues/13586) but they sent me to open a PR, refering to their [documentation](http://opam.ocaml.org/doc/Packaging.html#If-the-project-is-hosted-on-Github) which suggests you need to create a version tag in git with `git tag` and `git push` then use `opam publish`. Can you do that? It has to be a maintainer with github repository access doing it.

**Comment by bikallem** [comment]
Sure. I will do it tonight.

**Comment by bikallem** [comment]
@fare PR https://github.com/ocaml/opam-repository/pull/13831.

Thanks for reminding me.

**Pull request merged**
